version: '3'
services:
  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_NUMBER=${BUILD_NUMBER}
    image: ${imageName}:${BUILD_NUMBER}
    deploy:
      replicas: 1
    ports:
      - "3000:3000"
